### ISSUE TITLE
is this out of date now ?

### ISSUE THREAD

**Issue by joeblew99** [ContainerSolutions/terraform-nomad#2]
I user terraform to bring up the infrastructure on CGE, with Coreos as my base server type.
But i cant wokr out how to get Nomad onto all of them as agents.

**Comment by thijsschnitger** [comment]
I'm not sure if it still works, I have not been following the progress on Nomad lately. I plan to take a look at it before the end of the year.

**Comment by thijsschnitger** [comment]
I can confirm it still works. However the url for downloading nomad changed. I'll update the install.sh

**Comment by thijsschnitger** [comment]
this commit should fix it https://github.com/ContainerSolutions/terraform-nomad/commit/61c2e302713752ea4644611a6b9ea209e36e17bc
